spring.application.name=monitoring
server.port=8082

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Console H2 (exactement comme LowCarb)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# DataBase H2 - R2DBC (exactement comme LowCarb, juste le nom du fichier change)
spring.sql.init.mode=always
spring.r2dbc.initialization-mode=always
spring.r2dbc.properties.autoCommit=true
spring.r2dbc.url=r2dbc:h2:file:///./monitoring-data;AUTO_SERVER=TRUE
spring.r2dbc.username=ed
spring.r2dbc.password=

# DataBase H2 - JDBC pour la console H2
spring.datasource.url=jdbc:h2:file:///./monitoring-data;AUTO_SERVER=TRUE
spring.datasource.username=ed
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# Logging
logging.level.io.eddvance.production.monitoring=DEBUG
logging.level.io.r2dbc.h2=DEBUG

# Actuator / Prometheus endpoints
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=monitoring
