spring.application.name=monitoring
server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.sql.init.mode=always
spring.r2dbc.initialization-mode=always
spring.r2dbc.properties.autoCommit=true
spring.r2dbc.url=r2dbc:h2:file:///./monitoring-data;AUTO_SERVER=TRUE
spring.r2dbc.username=ed
spring.r2dbc.password=

spring.datasource.url=jdbc:h2:file:///./monitoring-data;AUTO_SERVER=TRUE
spring.datasource.username=ed
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

logging.level.io.eddvance.production.monitoring=DEBUG
logging.level.io.r2dbc.h2=DEBUG

management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=monitoring
